apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: NodePort
  selector:
    app: node_api-app
  ports:
      - nodePort: 31001
        protocol: TCP
        port: 8073
